# Generated by Django 2.1.4 on 2018-12-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181209_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрытый пост'),
        ),
    ]
